-- Supabase table creation script for School Marketplace
-- Run these statements in the Supabase SQL editor (Project > SQL > New query)

-- users table
create table public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password text not null,
  role text not null default 'user',
  location text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- products table
create table public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  price numeric(10,2) not null check (price >= 0),
  category text not null check (category in ('uniforms','books','bags','shoes','stationery','other')),
  images text[] default '{}',
  location text,
  product_type text not null default 'direct_sell' check (product_type in ('direct_sell','platform_sell')),
  seller_id bigint not null references public.users(id),
  approved boolean not null default false,
  stock integer not null default 1 check (stock >= 0),
  condition text not null default 'new' check (condition in ('new','like_new','good','fair')),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create index on public.products (seller_id);
create index on public.products (category);
create index on public.products (approved);
create index on public.products (product_type);

-- carts table
create table public.carts (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id),
  products jsonb not null default '[]',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- orders table
create table public.orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id),
  products jsonb not null,
  total_amount numeric(12,2) not null check (total_amount >= 0),
  payment_status text not null default 'pending' check (payment_status in ('pending','paid','failed','refunded')),
  order_status text not null default 'pending' check (order_status in ('pending','processing','shipped','delivered','cancelled')),
  shipping_address text default '',
  payment_method text not null default 'cash_on_delivery' check (payment_method in ('cash_on_delivery','online','wallet')),
  transaction_id text default '',
  razorpay_order_id text default '',
  razorpay_payment_id text default '',
  razorpay_signature text default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create index on public.orders (user_id);
create index on public.orders (payment_status);
create index on public.orders (order_status);
create index on public.orders (created_at desc);
